name: Manual Staging Deploy 

on:
  workflow_dispatch:
    inputs:
      deploy_django:
        description: 'Deploy Django App'
        required: true
        type: boolean
        default: false

env:
  PROJECT_ID: '${{ secrets.PROJECT_ID }}'
  REGION: '${{ vars.REGION }}'

jobs:
  Django-App:
    runs-on: ubuntu-latest
    name: Staging Deploy Django
    timeout-minutes: 15
    if: github.event.inputs.deploy_django == 'true' || github.event.inputs.django_migration == 'true'

    env:
      SERVICE: '${{ vars.SERVICE }}'
      GAR_NAME: '${{ vars.GAR_NAME }}'
      GCS_BUCKET: '${{ vars.GCS_BUCKET }}'

    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        name: Setup cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('services/django-app/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/django-app/requirements.txt

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Collect static files
        run: |
          cd services/django-app
          python manage.py collectstatic --noinput
          gcloud storage rsync -r staticfiles gs://'${{ vars.GCS_BUCKET }}'/static
