name: Pull Request QA

on:
  push:
    branches:
      - master

jobs:
  check-changes:
    runs-on: ubuntu-latest
    name: Check changes
    timeout-minutes: 10

    permissions:
      contents: read
      pull-requests: read

    outputs:
      changes-django: ${{ steps.check.outputs.django }}
      changes-flask: ${{ steps.check.outputs.flask }}

    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: check
        with:
          filters: |
            django:
              - 'services/django-app/**'
            flask:
              - 'services/flask-app/**'

      - name: Set output for changes
        id: set-output
        run: |
          echo "changes-django=${{ steps.check.outputs.django }}" >> $GITHUB_ENV
          echo "changes-flask=${{ steps.check.outputs.flask }}" >> $GITHUB_ENV

  Django-App:
    runs-on: ubuntu-latest
    name: Django QA
    timeout-minutes: 10
    needs: check-changes
    if: needs.check-changes.outputs.changes-django == 'true'

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.2"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('services/django-app/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/django-app/requirements-dev.txt

      - name: Run Flake8
        run: |
          cd services/django-app
          flake8 .

      - name: Run tests
        run: |
          cd services/django-app
          pytest
        env:
          DATABASE_NAME: postgres
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432


  Flask-App:
    runs-on: ubuntu-latest
    name: Flask QA
    timeout-minutes: 10
    needs: check-changes
    if: needs.check-changes.outputs.changes-flask == 'true'

    env:
      APP_SETTINGS: "src.config.TestingConfig"

    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('services/flask-app/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/flask-app/requirements-dev.txt

      - name: Run Flake8
        run: |
          cd services/flask-app
          flake8 .

      - name: Run tests
        run: |
          cd services/flask-app
          pytest
